### ISSUE TITLE
 ERROR  failed to run model Error: java.lang.String[][] cannot be cast to java.lang.String[]

### ISSUE THREAD

**Issue by ArkaitzSKR** [sirramin/onnxruntime-whisper-react-native#1]
Hello! I am using your example to implement a speech to text application and I can't get the model to recognize my audio.

The model loads fine, the audio is recorded fine, but then when running the model, this error appears:

  ERROR failed to run model Error: java.lang.String[][] cannot be cast to java.lang.String[]

I have tried running your application and it also has the same error.

I understand that you got it to work, let's see if you can see the error.

Thank you very much in advance.

**Comment by sirramin** [comment]
Hi, I fix the error in new commit try it.
It is from a inconsistency between onnx runtime and whisper model.

**Comment by ArkaitzSKR** [comment]
Thank you so much. The bug has been fixed.
